# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data

```{r}
setwd("/Users/rodolfofernandez/Desktop/RepData_PeerAssessment1")
act.data <- read.csv("activity.csv")
names(act.data)
head(act.data)
summary(act.data)
#process dates
library(lubridate)   
act.data$date <- ymd(act.data$date)
```
## What is mean total number of steps taken per day?
```{r}
hist(tapply(act.data$steps , act.data$date, sum, na.rm = T), col = "purple", xlab="Total steps per day", main = "Hist of total steps per day")
mean(tapply(act.data$steps , act.data$date, sum, na.rm = T), na.rm=T)
median(tapply(act.data$steps , act.data$date, sum, na.rm = T), na.rm=T)
```
## What is the average daily activity pattern?
```{r}
avg.ints <- tapply(act.data$steps , act.data$interval, mean, na.rm = T)
plot(as.numeric(rownames(avg.ints)), avg.ints, type = "l", lwd = 2, col = "blue", main = "Average interval steps across all days", xlab = "Interval")
```
## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
